FROM node:lts-alpine3.17

EXPOSE 3000

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./

RUN npm install

COPY . .

# Build the Astro project for production
# This will create a /dist directory with the built files
# the node entry point will be /dist/server/entry.mjs
RUN astro build --outDir ./dist

# Serve the built files using Node.js

CMD [ "node", "./dist/server/entry.mjs" ]

